// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBky6TZbu8XjYa0s1K_DQaCico2YtPYa0s',
    appId: '1:872970425390:web:fc3d4a85ff01fec451fbbf',
    messagingSenderId: '872970425390',
    projectId: 'dun-bun-finance',
    authDomain: 'dun-bun-finance.firebaseapp.com',
    storageBucket: 'dun-bun-finance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPK3j8e8ts_Nr2LQWlwWBa3I9cjqJvwL4',
    appId: '1:872970425390:android:f50df7083870acec51fbbf',
    messagingSenderId: '872970425390',
    projectId: 'dun-bun-finance',
    storageBucket: 'dun-bun-finance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOxNwqlZeE_QI3ObxsHW37NDJLogKdFGI',
    appId: '1:872970425390:ios:7860e134c178410951fbbf',
    messagingSenderId: '872970425390',
    projectId: 'dun-bun-finance',
    storageBucket: 'dun-bun-finance.firebasestorage.app',
    iosBundleId: 'com.example.dunBunFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOxNwqlZeE_QI3ObxsHW37NDJLogKdFGI',
    appId: '1:872970425390:ios:7860e134c178410951fbbf',
    messagingSenderId: '872970425390',
    projectId: 'dun-bun-finance',
    storageBucket: 'dun-bun-finance.firebasestorage.app',
    iosBundleId: 'com.example.dunBunFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3kEIbegrcAS-XwHMgqnQhSrIUwCN302g',
    appId: '1:872970425390:web:dc51e02d043a7e3651fbbf',
    messagingSenderId: '872970425390',
    projectId: 'dun-bun-finance',
    authDomain: 'dun-bun-finance.firebaseapp.com',
    storageBucket: 'dun-bun-finance.firebasestorage.app',
  );
}
